---
project_name: tsf
dist: bin/dist

builds:
  - id: tsf
    binary: tsf
    goos:
      - darwin
      - linux
      - windows
    env:
      - GOFLAGS={{ .Env.GOFLAGS }}
      - CGO_ENABLED={{ .Env.CGO_ENABLED }}
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS }}
    main: cmd/tsf/main.go
    goarch:
      - arm64
      - amd64
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commitID={{.Commit}}
