---
apiVersion: v2
name: tssc-integrations
description: TSSC Integrations
type: application
version: "1.7.0"
annotations:
  tssc.redhat-appstudio.github.com/product-name: ("OpenShift GitOps" || "Advanced Cluster Security")
  tssc.redhat-appstudio.github.com/integration/requires: acs, gitops, (artifactory || nexus || quay), (bitbucket, github, gitlab)
