{{- $name := .Release.Name }}
{{- $context := . }}
{{- range .Values.appNamespaces.namespace_prefixes }}
  {{- $namespace := . }}
  {{- range tuple "ci" "development" "prod" "stage" }}
    {{- $sa := "default" }}
    {{- if eq . "ci" }}
      {{- $sa = "pipeline" }}
    {{- end }}
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "common.labels" $context | nindent 4 }}
  name: patch-serviceaccounts
  namespace: {{ $namespace }}-{{ . }}
spec:
  serviceAccountName: {{ $name }}
  restartPolicy: Never
  initContainers:
    #
    # Copying the scripts that will be used on the subsequent containers, the
    # scripts are shared via the "/scripts" volume.
    #
    {{- include "common.copyScripts" $context | nindent 8 }}
  containers:
    - name: patch-serviceaccounts
      image: registry.redhat.io/openshift4/ose-tools-rhel9:v4.19
      command:
        - /scripts/patch-serviceaccounts.sh
      args:
        - "--secret"
        - "tssc-image-registry-auth"
        - "--serviceaccount"
        - "{{ $sa }}"
      volumeMounts:
        - name: scripts
          mountPath: /scripts
      securityContext:
        runAsNonRoot: false
        allowPrivilegeEscalation: false
  volumes:
    - name: scripts
      emptyDir: {}
  {{- end }}
{{- end }}
