{{- $name := .Release.Name }}
{{- range .Values.appNamespaces.namespace_prefixes }}
  {{- $namespace := . }}
  {{- range tuple "ci" "development" "prod" "stage" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}-{{ . }}
  labels: {{- include "common.postDeployDeleteLabels" $ | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}-serviceaccount-patcher
  namespace: {{ $namespace }}-{{ . }}
  labels: {{- include "common.postDeployDeleteLabels" $ | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}-serviceaccount-patcher
  namespace: {{ $namespace }}-{{ . }}
  labels: {{- include "common.postDeployDeleteLabels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}-serviceaccount-patcher
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
  {{- end }}
{{- end }}
